<?php

namespace USTA\MemberBundle\Repository;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends \Doctrine\ORM\EntityRepository
{
  public function getFamilyWithAll($id)
  {
    $em = $this->getEntityManager();
    $family = $this->find($id);

    // if($family !== null){
    //   $members = $em->getRepository('USTAMemberBundle:Member')->findByFamily($id);
    //   $addresses = $em->getRepository('USTAMemberBundle:Address')->findByFamily($id);
    //   $phones = $em->getRepository('USTAMemberBundle:Phone')->findByFamily($id);
    //   $emails = $em->getRepository('USTAMemberBundle:Email')->findByFamily($id);
    //
    //   $family
    //     ->addMembers($members)
    //     ->addAddresses($addresses)
    //     ->addPhones($phones)
    //     ->addEmails($emails)
    //   ;
    // }

    return $family;
  }
}
