imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@USTADashboardBundle/Resources/config/services.yml" }
    - { resource: "@USTAAccountBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        about:
          description: "<strong>UStA</strong> (<strong>U</strong>ser <strong>St</strong>orage <strong>A</strong>pplication) est une application Web de gestion des cotisations annuelle des membres d'une association."
          developers: "Yasin SENEL & Sadetdin EYILI"
          OS: "Linux"
          place: "Bordeaux <3"
          version: "0.0.1 Alpha"
          technologies:
            - icon_class: "fa-lg fa-fw fa fa-server"
              intro: "Un serveur HTTP"
              name: "Apache"
            - icon_class: "fa-lg fa-fw fa fa-database"
              intro: "Un serveur de Base de Donnée"
              name: "MySQL"
            - icon_class: "fa-lg fa-fw fa fa-code"
              intro: "Le langage PHP avec le framework"
              name: "Symfony"
            - icon_class: "fa-lg fa-fw fa fa-css3"
              intro: "Le framework HTML CSS et JS"
              name: "Bootstrap"
            - icon_class: "fa-lg fa-fw fa fa-github"
              intro: "Le service d'hébergement et de versionnement du code"
              name: "GitHub"
            - icon_class: "fa-lg fa-fw fa fa-fort-awesome"
              intro: "Le pack d'icônes"
              name: "Font Awesome"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                MATCH: USTA\MemberBundle\DoctrineExtensions\MatchAgainstFunction

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class: USTA\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    registration:
        form:
            type: USTA\UserBundle\Form\RegistrationFormType
