<?php

namespace USTA\AccountBundle\Repository;

/**
 * MembershipFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipFeeRepository extends \Doctrine\ORM\EntityRepository
{
  public function myFindByFamily($id)
  {
    //http://stackoverflow.com/questions/17534796/match-against-script-is-not-working-with-symfony2
    $qb = $this->getEntityManager()->createQueryBuilder();
    return $qb
      ->select('mf')
      ->from('USTAAccountBundle:MembershipFee', 'mf')
      ->join('mf.members','m')
      ->addselect('m')
      ->join('m.family','f')
      ->where('f.id = :id')
      ->setParameter('id', $id)
      ->getQuery()
      ->getResult()
      ;
  }
}
