parameters:
  usta_member.doctrine.prefix: usta_

services:
  # prefix database table
  usta_member.doctrineprefix_subscriber:
    class: USTA\MemberBundle\DoctrineExtensions\TablePrefix
    arguments: [%usta_member.doctrine.prefix%]
    tags:
      - { name: doctrine.event_subscriber }
  # custom form type
  usta_member.form.type.gender:
      class: USTA\MemberBundle\Form\Type\GenderType
      tags:
          - { name: form.type, alias: gender }
  usta_member.form.type.relationship:
      class: USTA\MemberBundle\Form\Type\RelationshipType
      tags:
          - { name: form.type, alias: relationship }
  usta_member.form.type.addresstype:
      class: USTA\MemberBundle\Form\Type\AddressTypeType
      tags:
          - { name: form.type, alias: addresstype }
  usta_member.form.type.phonetype:
      class: USTA\MemberBundle\Form\Type\PhoneTypeType
      tags:
          - { name: form.type, alias: phonetype }
  usta_member.form.type.emailtype:
      class: USTA\MemberBundle\Form\Type\EmailTypeType
      tags:
          - { name: form.type, alias: emailtype }
#    usta_member.example:
#        class: USTA\MemberBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
