services:
#    usta_user.example:
#        class: USTA\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    check_email_and_code_validator:
        class: USTA\UserBundle\Validator\CheckEmailAndCodeValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            -
                name: validator.constraint_validator
                alias: check_email_and_code
    fos_user.doctrine_registry:
        alias: doctrine
